apiVersion: apps/v1

kind: Deployment

metadata:
  name: streamlit-deployment

spec:
  replicas: 4 # Let's have 4 pods to handle more incoming traffic!
  selector:
    matchLabels:
      app: streamlit

  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: app:latest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/app/.streamlit"
            name: streamlit-secrets
            readOnly: true
        ports:
        - containerPort: 8501
        args: ["streamlit", "run", "f1dashboard/Introduction.py"]
      volumes:
        - name: streamlit-secrets
          secret:
            secretName: streamlit-secrets
      restartPolicy: Always
